apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-deployment
  labels:
    app: assessment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assessment
  template:
    metadata:
      labels:
        app: assessment 
    spec:
      containers:
      - name: nodeserver
        image: dhananjay17jan/assessment:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: assessment-service
spec:
  selector:
    app: assessment 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
