apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-deployment
  labels:
    app: assessment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assessment
  template:
    metadata:
      labels:
        app: assessment 
    spec:
      containers:
      - name: nodeserver
        image: dhananjay17jan/assessment:latest
        ports:
        - containerPort: 3000
